# Description: Freescale iMX firmware
# URL: http://www.freescale.com
# License: Freescale EULA

name=firmware-imx
version=5.2
release=1
source=(http://www.freescale.com/lgfiles/NMG/MAD/YOCTO//$name-$version.bin)

build() {
    chmod +x $name-$version.bin
    ./$name-$version.bin --force --auto-accept

    cd $name-$version

    # Install Freescale VPU firmware
    install -d $PKG/lib/firmware/vpu
    install -D firmware/vpu/* $PKG/lib/firmware/vpu
}
