# Description: Freescale iMX GPU binaries
# URL: http://www.freescale.com
# License: Freescale EULA

name=imx-gpu-viv
version=5.0.11.p4.4
release=1
source=(http://www.nxp.com/lgfiles/NMG/MAD/YOCTO/$name-$version-hfp.bin
        http://repository.timesys.com/buildsources/i/$name/$name-$version/$name-$version-Makefile.patch)

build() {
    chmod +x $name-$version-hfp.bin
    ./$name-$version-hfp.bin --force --auto-accept

    cd $name-$version-hfp

    patch -p1 -i $SRC/$name-$version-Makefile.patch

    make BACKEND=fb \
         DESTDIR=$PKG \
         install

    # Remove samples to save size
    #rm -rf $PKG/opt
}
