# Description: Freescale iMX gstreamer plugins
# URL: https://github.com/Freescale/gstreamer-imx
# License: LGPLv2

name=gstreamer-imx
version=gitdfd79250
release=1
source=(http://mirror.mini-distribution.io/nxp/$name-$version.tar.xz)
depends=(gst-plugins-base gst-plugins-bad native/linux-source libfslvpuwrap firmware-imx libimxvpuapi)

build() {
   cd $name-$version

   CC=$HOST-gcc \
   ./waf configure --prefix=$PKG/usr --kernel-headers=$NATIVE_SYSROOT/usr/src/linux/include
   ./waf
   ./waf install
}
